# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
my:
  app:
    db:
      driver: MySql-qa
      url: jdbc-oracle-qa
      username: Rajesh-qa
      password: abc-qa
      database: testdb-qa
