# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
my:
  app:
    db:
      driver: Oracle
      url: jdbc-oracle
      username: Rajesh
      password: abc
      database: testdb
